### ISSUE TITLE
React 15

### ISSUE THREAD

**Issue by mattmo** [aickin/react-dom-stream#14]
Thank for making this library! We're running into TTFB latency issues with a sever side rendered React app and we're currently evaluating using react-dom-stream. Now that React 15.0 is in RC, we wanted to see if you were planning to update react-dom-stream to support it? Also, have you spoken with the react team at all about taking your changes upstream?

**Comment by aickin** [comment]
Sorry for the delay; I've been traveling (SXSW) and super busy.

I am planning to try to port React 15.0, but I haven't started yet.

I haven't spoken with the React team; I'm afraid they are interested in the idea but won't like the way I coded it. I'm trying to find a more compact, maintainable way to write the code so that it can be accepted more easily. That'll be a goal of working on React 15.

It's worth noting that I think using react-dom-stream as is is pretty low risk. In most cases, it should only require a couple lines to switch from react-dom to react-dom-stream, so it's easy to switch back if it's not working for you (or if I take too long to adapt 15.0).

Also: if you are having significant latency issues, please also check out my talk on server-side React perf, and make sure you're doing steps 0-3: https://www.youtube.com/watch?v=PnpfGy7q96U

Closing because I think I've answered your question. Thanks for considering react-dom-stream!
