### ISSUE TITLE
prepend stream with a <!DOCTYPE html> for older browsers?

### ISSUE THREAD

**Issue by mattkrick** [aickin/react-dom-stream#15]
currently, i'd have to prepend this after the stream is created since react generates my entire html & react doesn't recognize that tag. I think it'd be a nice addition to move the prepend part inside this package.

**Comment by wenzowski** [comment]
This is probably simple, ref mattkrick/meatier#128

**Comment by aickin** [comment]
@mattkrick thanks for the feedback!

I'm a little confused about the request, though. If you have some code like this:

```javascript
ReactDomStream.renderToStaticMarkup(<Foo/>).pipe(res);
```

You should be able to change it to this without a problem:

```javascript
res.write("<!DOCTYPE html>");
ReactDomStream.renderToStaticMarkup(<Foo/>).pipe(res);
```

Does that make sense, or am I missing something? Thanks!

**Comment by mattkrick** [comment]
Yep, that'll do it! I'm just wondering what your thoughts are on internalizing that 1 line. Reason being is I never added the `res.write("<!DOCTYPE html>");` and I didn't see a problem until someone tried it out on an older browser & it failed, so I'm willing to bet others are probably doing the same dumb thing I did & are getting breakages when legacy browsers hit their sites.

**Comment by jbrantly** [comment]
FWIW, I think it's slightly harder in Koa since the convention is more like:

```
ctx.body = ReactDomStream.renderToStaticMarkup(<Foo/>)
```

Having this built-in would be a big help there.

**Comment by aickin** [comment]
> Yep, that'll do it! I'm just wondering what your thoughts are on internalizing that 1 line. 

I hear and appreciate your argument for it, but I'm leaning against it, for a few reasons:

1. react-dom doesn't add the doctype, and I want to make it as easy as possible to drop in react-dom-stream. If someone has correct working code in react-dom that manually adds a doctype, then switching to react-dom-stream will have a duplicate doctype. 
2. renderToStaticMarkup can generate document fragments as well (i.e. Just a div), so this proposed code would have to detect whether or not it is being used to generate a full html document before adding the doctype. That isn't that hard to do, but it feels a little odd to me from an API perspective to have it sometimes add an extra bit of markup and sometimes not. 
3. There's a workaround. 

I should at least update the documentation to include writing out the doctype as a best practice. I'm also thinking of writing a simple transform stream that would prepend the doctype, so that you could write something more like this:

```javascript
const doctypeStream = require("doctype-stream");
ReactDomStream.renderToStaticMarkup(<Foo/>)
  .pipe(doctypeStream())
  .pipe(res);
```

What do you think? Does this make sense?

**Comment by mattkrick** [comment]
good thoughts & good arguments!
my idea was exactly like you said in point 2: see if the buffer starts with `<HTML`, if so, add the doctype. To me, it doesn't feel wrong because you're doing exactly what new browsers do anyways: correct an erroneous stream, as there's never a reason you'd want to send a full doc without the doctype tag. Alternatively, if you were open to expanding the api, instead of the proposed `doctype-stream`, i'd say just go for something like `ReactDomStream.renderDocToStaticMarkup(<Foo/>).pipe(res)`, but an extra method to solve 1-3 lines may not be worth the added footprint.

**Comment by Jerry-Hong** [comment]
so how add !doctype with koa 2 ?

**Comment by michaeldzjap** [comment]
For koa2:
```
import { PassThrough } from 'stream'
...
const stream = new PassThrough()
stream.write('<!DOCTYPE html>')
const body = ReactDomStream.renderToStaticMarkup(<Foo/>)
body.pipe(stream, {end: false})
body.on('end', _ => stream.end())
ctx.type = 'text/html'
ctx.body = stream
```
Not really sure if you need to explicitly end the stream.
```
body.pipe(stream)
ctx.type = 'text/html'
ctx.body = stream
```
seems to work too.
