### ISSUE TITLE
Preventing errors from crashing node

### ISSUE THREAD

**Issue by jbrantly** [aickin/react-dom-stream#17]
I'm running into an issue where errors during the React render are crashing the node process. Here is a simple repro:

```javascript
var React = require('react')
var ReactDOMStream = require('react-dom-stream/server')

var Component = React.createClass({
  render: function() {
    null.doSomething() // throws
    return React.createElement('span')
  }
})

var stream = ReactDOMStream.renderToString(React.createElement(Component))

// this should theoretically prevent node from crashing
stream.on('error', function(err) {
  console.log(err)
})

stream.on('readable', function() {
  var data
  while (null !== (data = this.read())) {
    console.log("Data:", data.toString('utf-8'))
  }
});

// application should keep running
setTimeout(null, 10000)
```

My understanding is that unhandled errors in streams will crash node, but even if I add an error handler as shown above the process still crashes. Am I missing something?

**Comment by aickin** [comment]
Thanks for the bug report!

I've integrated your test case into the test suite and am getting it to fail as well; I'll probably look at how to fix it tomorrow. Thanks!

**Comment by aickin** [comment]
Turned out there were two ugly error handling bugs on my part here. For posterity:
1. I assumed that node streams would translate a thrown error into an emitted error event. It does not, so a thrown error in the `_read` method (which is the method that calls the render functions) just throws up the stack. I fixed this by wrapping the entire `_read` method in a try-catch and emitting the error in the catch block.
2. Even after that, it still didn't work, and it turned out that's because of another error weirdness in node streams. In `renderToString`, I pipe the markup stream through a transform stream that calculates the react checksum, and I return the resulting stream. Unfortunately, when an error is emitted in a Readable, it doesn't propagate through the pipe. So, the stream you were adding an error handler to was not the stream that was actually emitting the error, and the error was going unhandled. I wrote a line to manually propagate the error, and the tests now pass. Yeehaw.

So: should be fixed in v0.5.1, which is on npm now. THANKS!

**Comment by jbrantly** [comment]
Thanks a bunch for addressing this.

There is one additional case that I _believe_ should be handled automatically by react-dom-stream. For `renderToStaticMarkup`, you allow embedding streams using `dangerouslySetInnerHTML`. In these cases I think any errors on the inner streams should be automatically propagated to the parent stream. Currently a [standard SSR setup](https://github.com/aickin/react-dom-stream#combining-rendertostaticmarkup-and-rendertostring-to-serve-a-page) will still crash if the error occurred on the inner stream (which is actually the more common case).

**Comment by CrocoDillon** [comment]
@jbrantly did you find a solution to the problem described in your last comment? Running into the same issue. I need the error in the outer stream to serve the correct status (if sending headers is still possible at that point) and 404/500 error components.

**Comment by jbrantly** [comment]
Yea.. you just have to make sure to put an onerror handler on both the inner and the outer stream. In my case I'm using Koa2. Koa already handles the outer stream fine when you do `ctx.body = stream`. The issue was the inner stream which is used with `dangerouslySetInnerHTML`. So I pass my ctx to where the inner stream is created and manually wire it up:

```
innerStream.on('error', ctx.onerror.bind(ctx))
```

Obv YMMV depending on your framework.

**Comment by CrocoDillon** [comment]
Nice and dirty! I would prefer if someday errors will propagate automatically when using `react-dom-stream` but this is a great help for now, thanks!
